AllCops:
  Exclude:
    - 'second_level_cache.gemspec'
  TargetRubyVersion: 2.4

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Security/Eval:
    Enabled: false

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/LineLength:
  Max: 1200

Metrics/ClassLength:
  Max: 1200

Metrics/MethodLength:
  Max: 1200

Metrics/ModuleLength:
  Max: 1200

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Rails:
  Enabled: true

Rails/TimeZone:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/GuardClause:
  Enabled: false

Rails/FindBy:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

Style/EvalWithLocation:
  Exclude:
    - "test/active_record_test_case_helper.rb"
