language: ruby
rvm:
  - 2.4.0
  - 2.5.0
gemfile:
  - gemfiles/Gemfile-5-2
  - gemfiles/Gemfile-edge
matrix:
  allow_failures:
    - gemfile: gemfiles/Gemfile-edge
script:
  - bundle exec rake test
  - bundle exec rubocop
